### PR TITLE
SAGE-1581: add manifest cloud sync support

### PR DESCRIPTION
**Pull request by jswantek**
sync manifest to host file and create kubernetes configmap

### CODE REVIEW

**Comment by jswantek** [comment]
Output

```
creating configmap [waggle-node-manifest from file [/etc/waggle/node_manifest.json]]
configmap/waggle-node-manifest replaced
waggle-node-manifest updated
syncing manifest (/etc/waggle/node-manifest-v2.json and cm waggle-node-manifest-v2) from https://auth.sagecontinuum.org/manifests/W030/
online manifest (https://auth.sagecontinuum.org/manifests/W030/) found, downloaded to: /tmp/node-manifest-v2.json
creating configmap [waggle-node-manifest-v2 from file [/etc/waggle/node-manifest-v2.json]]
configmap/waggle-node-manifest-v2 replaced
waggle-node-manifest-v2 updated
creating configmap [waggle-data-config from file [./data-config.json]]
waggle-data-config already exists, not updating.
```

**Comment by jswantek** [comment]
When the manifest doesnt exist in the cloud

```
syncing manifest (/etc/waggle/node-manifest-v2.json and cm waggle-node-manifest-v2) from https://auth.sagecontinuum.org/manifests/W039/
failed to download manifest (https://auth.sagecontinuum.org/manifests/W039/)
creating configmap [waggle-data-config from file [./data-config.json]]
waggle-data-config already exists, not updating.
```

**Comment by jswantek** [comment]
New results using the hashed (kustomize)

```
waggle-node-manifest                             1      209d
waggle-node-manifest-v2-77mb9m6h87               1      72s
```

running it a 2nd time got me
```
configmap/waggle-node-manifest-v2-77mb9m6h87 unchanged
```

a 3rd time after doing a small change in the admin portal
```
configmap/waggle-node-manifest-v2-g62tct7t5b created

waggle-node-manifest                             1      209d
waggle-node-manifest-v2-77mb9m6h87               1      7m24s
waggle-node-manifest-v2-g62tct7t5b               1      41s
```

after going back to the original
```
configmap/waggle-node-manifest-v2-77mb9m6h87 unchanged
```

**Review by seanshahkarami — APPROVED** [review]
Looks good to me!

**Pull request merged**
